version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - FIREBASE_CONFIG
        - CHATBOT_WIDGET=${CHATBOT_WIDGET:-''}
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
